# docker compose up -d
# docker compose down
# docker compose config
# docker compose logs app -f
# docker compose up -d --build
# docker compose up -d --force-recreate postgres
# docker compose exec app sh
# docker compose ps -a
# docker compose exec app ls -la /run/secrets

services:

  postgres:
    image: postgres:17

    environment:
      POSTGRES_DB: ${ENV_POSTGRES_DB}
      POSTGRES_USER: ${ENV_POSTGRES_USER}
      #The application should not receive the database password as an environment variable.
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password

    secrets:
      # Docker secret is mounted with different filenames depending on the consumer:
      # PostgreSQL: /run/secrets/postgres_password
      - source: postgres_password
        target: postgres_password

    volumes:
      - postgres-data:/var/lib/postgresql/data

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${ENV_POSTGRES_USER} -d ${ENV_POSTGRES_DB}" ]
      interval: 5s
      timeout: 5s
      retries: 5

  mongo:
    image: mongo:7

    volumes:
      - mongo-data:/data/db
      - mongo-config:/data/configdb

    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    # it will build climbing-management-sb-app:latest when "docker compose up -d"
    # when we build it manually, we set the tag "docker build -t climbing-management-sb:2.0 ."
    build: .

    ports:
      - "${ENV_APP_PORT}:8080"

    # Docker mounts the container's root filesystem as read-only
    read_only: true

    # Explicitly give /tmp writable space:
    tmpfs:
      - /tmp

    environment:
      SPRING_PROFILES_ACTIVE: docker

      # container    .env / Compose
      # variable
      #   ↓           ↓
      APP_MONGO_DB: ${ENV_MONGO_DB}
      APP_POSTGRES_USER: ${ENV_POSTGRES_USER}
      APP_POSTGRES_DB: ${ENV_POSTGRES_DB}

    secrets:
      # Docker secret is mounted with different filenames depending on the consumer:
      # App: /run/secrets/spring.datasource.password
      - source: postgres_password
        target: spring.datasource.password

    depends_on:
      postgres:
        condition: service_healthy
      mongo:
     #  condition: service_started
        condition: service_healthy

volumes:
  postgres-data:
  mongo-data:
  mongo-config:

# A service can reference a secret only if that secret is declared at the top-level Compose scope.
secrets:
  postgres_password:
    file: ./secrets/spring.datasource.password