
# IntelliJ: Run ? Edit Configurations ? your Spring Boot configuration ? Active profiles : set to local
### spring.profiles.active=local

#### POSTGRES
spring.datasource.url=jdbc:postgresql://localhost:5432/climbing_management
spring.datasource.username=postgres
spring.datasource.password=root

#### MONGO
spring.mongodb.uri=mongodb://localhost:27017/climbing_management
spring.mongodb.database=climbing_management

