spring.application.name=climbing-management-sb
spring.datasource.url=jdbc:postgresql://localhost:5432/climbing_management
spring.datasource.username=postgres
spring.datasource.password=root

# Indica a Hibernate cómo gestionar el esquema de la base de datos.
# "update" crea las tablas que no existen y actualiza el esquema cuando
# detecta cambios en las entidades JPA, sin borrar los datos existentes.
# En este caso, al detectar CourseEntity, Hibernate crea la tabla "courses".
# update     ? desarrolla / aprendizaje
# validate   ? producción (comprueba, no modifica)
# create     ? recrea las tablas al arrancar
# create-drop ? crea al arrancar y elimina al apagar
spring.jpa.hibernate.ddl-auto=update

#ver el SQL que genera Hibernate.
spring.jpa.show-sql=true