




# logging.level.org.springframework.boot.context.config=DEBUG
# debug=true

#### POSTGRES
spring.datasource.url=jdbc:postgresql://postgres:5432/climbing_management
spring.datasource.username=postgres
spring.datasource.password=root

#### MONGO
spring.mongodb.uri=mongodb://mongo:27017/${MONGO_DB}
spring.mongodb.database=${MONGO_DB}

