




# logging.level.org.springframework.boot.context.config=DEBUG
# debug=true

#### POSTGRES
spring.datasource.url=jdbc:postgresql://postgres:5432/climbing_management
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.config.import=optional:configtree:/run/secrets/

#### MONGO
spring.mongodb.uri=mongodb://mongo:27017/${MONGO_DB}
spring.mongodb.database=${MONGO_DB}

