apiVersion: v1
kind: Secret

metadata:
  name: climbing-management-secret

type: Opaque

stringData:
  DB_PASSWORD: dummy_value_pls_change_it

# ConfigMap → non-sensitive configuration
# Secret    → sensitive configuration