apiVersion: v1
kind: Service

metadata:
  # postgres →becomes the DNS name your Spring Boot Pod can resolve
  name: postgres

# Spring Boot Pod
#      │
#      │ postgres:5432
#      ▼
# ┌─────────────────┐
# │ postgres        │  ← Kubernetes Service
# │ ClusterIP       │
# └────────┬────────┘
#          │
#          ▼
# PostgreSQL Pod
# 10.244.0.19:5432

spec:
  selector:
    # selector: app: postgres → tells the Service which Pods receive traffic
    app: postgres

  ports:
    - protocol: TCP
      # port: 5432 → port exposed by the Service
      port: 5432
      # targetPort: 5432 → port on the PostgreSQL Pod
      targetPort: 5432

  # ClusterIP → makes PostgreSQL accessible inside the Kubernetes cluster
  type: ClusterIP