apiVersion: apps/v1
kind: Deployment

metadata:
  name: postgres

spec:
  replicas: 1

  selector:
    matchLabels:
      app: postgres

  template:
    metadata:
      labels:
        app: postgres

    spec:
      containers:
        - name: postgres
          image: postgres:17

          ports:
            - containerPort: 5432

          env:
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: climbing-management-config
                  key: APP_POSTGRES_DB

            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: climbing-management-config
                  key: APP_POSTGRES_USER

            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: climbing-management-secret
                  key: DB_PASSWORD

          readinessProbe:
            exec:
              command:
                - sh
                - -c
                - pg_isready -U "$POSTGRES_USER" -d "$POSTGRES_DB"
            initialDelaySeconds: 5
            periodSeconds: 5

          livenessProbe:
            exec:
              command:
                - sh
                - -c
                - pg_isready -U "$POSTGRES_USER" -d "$POSTGRES_DB"
            initialDelaySeconds: 15
            periodSeconds: 10

          # Mount the persistent storage inside the PostgreSQL container.
          # volumeMounts → defines WHERE the volume is mounted inside the container.
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data

      # Define the storage available to the Pod.
      # volumes → defines WHERE the storage comes from.
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-pvc


#   PostgreSQL Pod
#         │
#         │ volumeMount
#         ▼
#   postgres-storage
#         │
#         │ uses
#         ▼
#     postgres-pvc
#         │
#         │ dynamically provisions
#         ▼
#   PersistentVolume